### ISSUE TITLE
Unable to build compiled code

### ISSUE THREAD

**Issue by destructor64** [allscale/allscale_runtime#20]
To quote from issue #15 

> Current master works fine for me.
The error you are running into is from a insieme test. Which is unrelated to the problem reported initially.
When calling the backend compiler from the allscale compiler, you should set the "ALLSCALE_WITH_HPX" define. If that's omitted, the serialization wrapper for HPX inside the AllScale API isn't enabled, which leads exactly to those problems.

That does not fix the problems in all cases it seems.

Find the code to compile as well as the console output here: https://gist.github.com/peterz-dps/e3ff88637d0a722bc0d7dda6aa308389

(latest runtime, latest HPX commit)

**Comment by sithhell** [comment]
That's actually a allscale_api problem. See here: https://github.com/allscale/allscale_api/pull/8

**Comment by destructor64** [comment]
Still not completely fixed

See the new output in log2.txt in the updated gist

**Comment by sithhell** [comment]
Not a runtime but an API issue.

**Comment by HerbertJordan** [comment]
Hi Thomas, if you identify an issue as a API issue, please provide additional details such that it can be corrected. The insight on the cause of the problem would be helpful.

**Comment by sithhell** [comment]
the problem should be resolved fully with https://github.com/allscale/allscale_api/pull/9

**Comment by sithhell** [comment]
The linked PR fixes the problem fully. https://github.com/allscale/allscale_api/pull/8 was merged without checking if it really solves the issue. The cause of the issue was that `allscale::utils::Vector<T,Dims>` wasn't serializable for all `Dims`.

**Comment by sithhell** [comment]
@peterz-dps please check if that PR solves your issue and comment there.

**Comment by destructor64** [comment]
That seems to fix it. @HerbertJordan is working on some additional changes he wants to integrate with this right now.

At least for now I can compile our tests without compiler-errors.

**Comment by HerbertJordan** [comment]
The problem turned out to be a bit more sophisticated.

There was a very subtile bug here: https://github.com/allscale/allscale_api/blob/master/code/utils/include/allscale/utils/serializer.h#L476

The HPX version of the serializer depends on the is_serializable trait of the utils. However, this itself is based on the serialization infrastructure which has been widely disabled through the HPX macros, e.g. for arrays or std::vectors. Thus, the trait was not recognizing serializable objects (like the Vector) any more. Essentially, the HPX enabling macro must not remove the utils serialization code for meta-programming reasons. Nevertheless, it will be dead code anyway.

This commit fixes those issues: https://github.com/allscale/allscale_api/commit/3a99bea64277ca3a049ca7e8a941d8092276bb08
